# NUMPY TUTORIAL

In [ ]:
#NumPy is a Python library.
1.NumPy is used for working with arrays.
2.NumPy is short for "Numerical Python".

In [2]:
import numpy as np        #this is main library we want to import it first

# Numpy Array Creation

In [2]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [3]:
# Display the type of an object
type(list1)

list

In [4]:
#Convert list to Numpy Array
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [6]:
#Memory address of an array object
arr1.data

In [7]:
# Display type of an object
type(arr1)

numpy.ndarray

In [9]:
#Datatype of array
arr1.dtype    # Convert Integer Array to FLOAT
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [10]:
# Generate evenly spaced numbers (space =1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Generate numbers between 0 to 100 with a space of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
# Generate numbers between 10 to 100 with a space of 10 in descending order
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [13]:
#Shape of Array
arr3 = np.arange(0,10);print(arr3)
arr3.shape

[0 1 2 3 4 5 6 7 8 9]


(10,)

In [14]:
# Dimension
arr3.ndim

1

In [15]:
# Datatype of object
arr3.dtype

dtype('int32')

In [16]:
# Length of array
len(arr3)

10

In [17]:
# Generate an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# Generate an array of ones with given shape
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
# Repeat 10 five times in an array
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [20]:
# Repeat each element in array 'a' thrice
a= np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [21]:
# Array of 10's
np.full(5,10)

array([10, 10, 10, 10, 10])

In [22]:
# Generate array of Odd numbers
ar1 = np.arange(1,20)
ar1[ar1%2 ==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
# Generate array of even numbers
ar1 = np.arange(1,20)
ar1[ar1%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
# Create an array of random values
np.random.random(4)

array([0.12984108, 0.17137794, 0.76111933, 0.72808506])

In [25]:
# Generate an array of Random Integer numbers
np.random.randint(0,500,5)

array([  2, 226, 486, 421, 132])

In [26]:
# Using random.seed we can generate same number of Random numbers
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [28]:
# Generate array of Random float numbers
f1 = np.random.uniform(5,10, size=(10))
f1


array([6.96058759, 6.71589008, 8.64524854, 7.19286122, 5.29838948,
       6.99022128, 8.68997703, 5.91245865, 5.87725878, 7.65775687])

In [29]:
# Extract Integer part
np.floor(f1)


array([6., 6., 8., 7., 5., 6., 8., 5., 5., 7.])

In [30]:
# Truncate decimal part
np.trunc(f1)

array([6., 6., 8., 7., 5., 6., 8., 5., 5., 7.])

In [31]:
# Convert Float Array to Integer array
f1.astype(int)

array([6, 6, 8, 7, 5, 6, 8, 5, 5, 7])

In [32]:
# Normal distribution (mean=0 and variance=1)
b2 =np.random.randn(10)
b2


array([ 2.20742744,  0.52274247,  0.46564476,  0.72491523,  1.49582653,
        0.74658059, -1.10098526, -1.4103012 , -0.74765132, -0.98486761])

In [33]:
arr1

array([10, 20, 30, 40, 50, 60])

In [34]:
# Enumerate for Numpy Arrays
for index, value in np.ndenumerate(arr1):
 print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


# Operations on an Array


In [4]:
arr2 = np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
# Sum of all elements in an array
arr2.sum()

190

In [6]:
np.sum(arr2)

190

In [37]:
# Cumulative Sum
np.cumsum(arr2)


array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [38]:
# Find Minimum number in an array
arr2.min()


1

In [39]:
# Find MAX number in an array
arr2.max()


19

In [40]:
# Find INDEX of Minimum number in an array
arr2.argmin()

0

In [41]:
# Find INDEX of MAX number in an array
arr2.argmax()


18

In [42]:
# Find mean of all numbers in an array
arr2.mean()

10.0

In [43]:
# Find median of all numbers present in arr2
np.median(arr2)

10.0

In [44]:
# Variance
np.var(arr2)


30.0

In [45]:
# Standard deviation
np.std(arr2)


5.477225575051661

In [46]:
# Calculating percentiles
np.percentile(arr2,70)

13.6

In [47]:
# 10th & 70th percentile
np.percentile(arr2,[10,70])


array([ 2.8, 13.6])

# Operations on a 2D Array

In [8]:
A = np.array([[1,2,3,0] , [5,6,7,22] , [10 , 11 , 1 ,13] , [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [49]:
# SUM of all numbers in a 2D array
A.sum()

129

In [51]:
# MAX number in a 2D array
A.max()



22

In [52]:
# Minimum
A.min()

0

In [10]:
# Column wise mimimum value
np.amin(A, axis=0)

array([1, 2, 1, 0])

In [54]:
# Row wise mimimum value
np.amin(A, axis=1)


array([0, 5, 1, 3])

In [55]:
# Mean of all numbers in a 2D array
A.mean()

8.0625

In [56]:
# Mean
np.mean(A)


8.0625

In [57]:
# Median
np.median(A)

6.5

In [58]:
# 50 percentile = Median
np.percentile(A,50)

6.5

In [59]:
a=np.var(A)
b=np.std(A)
print(a)
print(b)

40.30859375
6.348904925260734


In [60]:
np.percentile(arr2,70)

13.6

In [62]:
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [61]:
# Enumerate for Numpy 2D Arrays
for index, value in np.ndenumerate(A):
 print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


# Reading elements of an array

In [64]:
a = np.array([7,5,3,9,0,2])
print(a)

[7 5 3 9 0 2]


In [65]:
# Access first element of the array
a[0]

7

In [66]:
# Access all elements of Array except first one.
a[1:]

array([5, 3, 9, 0, 2])

In [67]:
# Fetch 2nd , 3rd & 4th value from the Array
a[1:4]


array([5, 3, 9])

In [68]:
# Get last element of the array
a[-1]

2

In [69]:
a[-3:-1]

array([9, 0])

# Replace elements in array

In [70]:
ar = np.arange(1,20)
ar


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [72]:
# Replace EVEN numbers with ZERO
rep1 = np.where(ar % 2 == 0, 0 , ar)
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [73]:
ar2 = np.array([10, 20 , 30 , 10 ,10 ,20, 20])
ar2


array([10, 20, 30, 10, 10, 20, 20])

In [74]:
# Replace 10 with value 99
rep2 = np.where(ar2 == 10, 99 , ar2)
print(rep2)


[99 20 30 99 99 20 20]


In [75]:
p2 = np.arange(0,100,10)
p2

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [76]:
# Replace values at INDEX loc 0,3,5 with 33,55,99
np.put(p2, [0, 3 , 5], [33, 55, 99])
p2

array([33, 10, 20, 55, 40, 99, 60, 70, 80, 90])

# Missing Values in an array

In [77]:
a = np.array([10 ,np.nan,20,30,60,np.nan,90,np.inf])
a


array([10., nan, 20., 30., 60., nan, 90., inf])

In [78]:
# Search for missing values and return as a boolean array
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [79]:
# Index of missing values in an array
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

In [80]:
# Replace all missing values with 99
a[np.isnan(a)] = 99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [81]:
# Check if array has any NULL value
np.isnan(a).any()

False

In [82]:
A = np.array([[1,2,np.nan,4] , [np.nan,6,7,8] , [10 , np.nan , 12 ,13] , [14,15,16,17]])
A

array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [83]:
# Search for missing values and return as a boolean array
np.isnan(A)

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [84]:
# Index of missing values in an array
np.where(np.isnan(A))


(array([0, 1, 2], dtype=int64), array([2, 0, 1], dtype=int64))

# Stack Arrays Vertically


In [13]:
a = np.zeros(20).reshape(2,-1)                        #for same dividation
b = np.repeat(1, 20).reshape(2,-1)


In [14]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [87]:
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [88]:
np.vstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [89]:
a1 = np.array([[1], [2], [3]])
b1 = np.array([[4], [5], [6]])

In [90]:
a1


array([[1],
       [2],
       [3]])

In [91]:
b1

array([[4],
       [5],
       [6]])

In [92]:
np.vstack([a1,b1])


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Stack Arrays Horizontally


In [93]:
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [94]:
np.hstack([a1,b1])

array([[1, 4],
       [2, 5],
       [3, 6]])

# Common items between two Arrays

In [95]:
c1 = np.array([10,20,30,40,50,60])
c2 = np.array([12,20,33,40,55,60])

In [96]:
np.intersect1d(c1,c2)

array([20, 40, 60])

# Remove Common Elements

In [97]:
np.setdiff1d(c1,c2)

array([10, 30, 50])

# Process Elements on Conditions


In [99]:
a = np.array([1,2,3,6,8])
b = np.array([10,2,30,60,8])
np.where(a == b) # returns the indices of elements in an input array where the given condition is satisfied.

(array([1, 4], dtype=int64),)

In [100]:
# Return an array where condition is satisfied
a[np.where(a == b)]

array([2, 8])

In [101]:
# Return all numbers betweeen 20 & 35
a1 = np.arange(0,60)
a1[np.where ((a1>20) & (a1<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [102]:
# Return all numbers betweeen 20 & 35 OR numbers divisible by 10
a1 = np.arange(0,60)
a1[np.where (((a1>20) & (a1<35)) | (a1 % 10 ==0)) ]


array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       40, 50])

In [103]:
# Return all numbers betweeen 20 & 35 using np.logical_and
a1[np.where(np.logical_and(a1>20, a1<35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

# Check for elements in an Array using isin()

In [104]:
a = np.array([10,20,30,40,50,60,70])
a


array([10, 20, 30, 40, 50, 60, 70])

In [105]:
# Check whether number 11 & 20 are present in an array
np.isin(a, [11,20])

array([False,  True, False, False, False, False, False])

In [106]:
#Display the matching numbers
a[np.isin(a,20)]

array([20])

In [107]:
b = np.array([10,20,30,40,10,10,70,80,70,90])
b


array([10, 20, 30, 40, 10, 10, 70, 80, 70, 90])

In [108]:
# Check whether number 10 & 70 are present in an array
np.isin(b, [10,70])


array([ True, False, False, False,  True,  True,  True, False,  True,
       False])

In [109]:
# Display the indices where match occurred
np.where(np.isin(b, [10,70]))


(array([0, 4, 5, 6, 8], dtype=int64),)

In [110]:
# Display the matching values
b[np.where(np.isin(b, [10,70]))]

array([10, 10, 10, 70, 70])

In [111]:
# Display the matching values
b[np.isin(b, [10,70])]

array([10, 10, 10, 70, 70])

# Reverse Array

In [113]:
a4 = np.arange(10,30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [114]:
# Reverse the array
a4[::-1]


array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [115]:
# Reverse the array
np.flip(a4)

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [3]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15] , [12,9,77,4]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [7]:
np.ndim(a3)

2

In [117]:
# Reverse ROW positions
a3[::-1,]

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 3,  2,  8,  1]])

In [118]:
# Reverse COLUMN positions
a3[:,::-1]

array([[ 1,  8,  2,  3],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [119]:
# Reverse both ROW & COLUMN positions
a3[::-1,::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 1,  8,  2,  3]])

# Sorting Array

In [8]:
a = np.array([10,5,2,22,12,92,17,33])

In [122]:
# Sort array in ascending order
np.sort(a)

array([ 2,  5, 10, 12, 17, 22, 33, 92])

In [123]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [124]:
a3 = np.array([[3,2,8,1] , [70,50,10,67] , [45,25,75,15]])
# Sort along rows
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [125]:
# Sort along rows
np.sort(a3,axis =1)


array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [126]:
# Sort along columns
np.sort(a3,axis =0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [9]:
a

array([10,  5,  2, 22, 12, 92, 17, 33])

In [129]:
# Sort in descending order
b = np.sort(a)
b = b[::-1]
# Sort in descending order
c = np.sort(a)
c=np.flip(c)
# Sort in descending order
a[::-1].sort()
print(b)
print(c)

[92 33 22 17 12 10  5  2]
[92 33 22 17 12 10  5  2]


# "N" Largest & Smallest Numbers in an Array

In [11]:
p = np.arange(0,50)
np.random.shuffle(p)

p

array([43, 27, 24,  8, 30,  3, 44, 39, 38, 26, 49, 19, 15, 12, 47, 22, 23,
       40, 45,  9, 46, 25,  1,  5, 32, 29, 13, 20, 34, 31, 37, 18,  7,  6,
        4, 36, 21, 42, 10, 48, 33, 14, 35, 16, 17, 28, 41,  2,  0, 11])

In [134]:
# Return "n" largest numbers in an Array
n = 4
p[np.argsort(p)[-n:]]

array([46, 47, 48, 49])

In [17]:
k=p[np.argsort(p)]
k[-4:]

array([46, 47, 48, 49])

In [135]:
# Return "n" largest numbers in an Array
p[np.argpartition(-p,n)[:n]]

array([49, 48, 47, 46])

In [24]:
# Return "n" smallest numbers in an Array
p[np.argsort(-p)[0:4]]


array([49, 48, 47, 46])

In [137]:
# Return "n" smallest numbers in an Array
p[np.argpartition(p,n)[:n]]

array([1, 0, 2, 3])

# Repeating Sequences

In [138]:
a5 = [10,20,30]
a5

[10, 20, 30]

In [139]:
# Repeat whole array twice
np.tile(a5, 2)

array([10, 20, 30, 10, 20, 30])

# Compare Arrays


In [140]:
d1 = np.arange(0,10)
d1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
d3 = np.arange(10,20)
d3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [142]:
d4 = d1[::-1]
d4

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [144]:
# Compare arrays using "allclose" function. If this function returns True then Arrays are equal
res1 = np.allclose(d1,d3)
res1

False

In [145]:
# Compare arrays using "allclose" function. If this function returns True then Arrays are equal
res1 = np.allclose(d1,d4)
res1

False

# Frequent Values in an Array


In [146]:
# unique numbers in an array
b = np.array([10,10,10,20,30,20,30,30,20,10,10,30,10])
np.unique(b)

array([10, 20, 30])

In [147]:
# unique numbers in an array along with the count E.g value 10 occurred maximum times (5 times) in an array "b"
val , count = np.unique(b,return_counts=True)
val,count


(array([10, 20, 30]), array([6, 3, 4], dtype=int64))

In [148]:
# 10 is the most frequent value
np.bincount(b).argmax()   #IT IS ALSO USE FOR MODE

10

# Read-Only Array


In [149]:
d5 = np.arange(10,100,10)
d5

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [150]:
# Make arrays immutable
d5.flags.writeable = False

In [151]:
d5[0] = 99

ValueError: assignment destination is read-only

# Vector Addition

In [26]:
v1 = np.array([1,2])
v2 = np.array([3,4])
v3 = v1+v2
v3 = np.add(v1,v2)
print('V3 =' ,v3)

V3 = [4 6]


# Multiplication of vectors


In [27]:
a1 = [5 , 6 ,8]
a2 = [4, 7 , 9]
print(np.multiply(a1,a2))

[20 42 72]


# Dot Product

In [28]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
dotp = a1@a2
print(" Dot product - ",dotp)
dotp = np.dot(a1,a2)
print(" Dot product usign np.dot",dotp)
dotp = np.inner(a1,a2)
print(" Dot product usign np.inner", dotp)
dotp = sum(np.multiply(a1,a2))
print(" Dot product usign np.multiply & sum",dotp)
dotp = np.matmul(a1,a2)
print(" Dot product usign np.matmul",dotp)
dotp = 0
for i in range(len(a1)):
 dotp = dotp + a1[i]*a2[i]
print(" Dot product usign for loop" , dotp)


 Dot product -  32
 Dot product usign np.dot 32
 Dot product usign np.inner 32
 Dot product usign np.multiply & sum 32
 Dot product usign np.matmul 32
 Dot product usign for loop 32


# Length of Vector

In [29]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(np.dot(v3,v3))
length

9.539392014169456

In [30]:
v3 = np.array([1,2,3,4,5,6])
length = np.sqrt(sum(np.multiply(v3,v3)))
length

9.539392014169456

# Normalized Vector

In [32]:
#First Method
v1 = [2,3]
length_v1 = np.sqrt(np.dot(v1,v1))
norm_v1 = v1/length_v1
length_v1 , norm_v1


(3.605551275463989, array([0.5547002 , 0.83205029]))

In [36]:
# Second Method
v1 = [2,3]
norm_v1 = v1/np.linalg.norm(v1)
norm_v1

array([0.5547002 , 0.83205029])

# Angle between vectors

In [34]:
#First Method
v1 = np.array([8,4])
v2 = np.array([-4,8])
ang = np.rad2deg(np.arccos( np.dot(v1,v2) / (np.linalg.norm(v1)*np.linalg.norm(v2))))
ang

90.0

In [35]:
#Second Method
v1 = np.array([4,3])
v2 = np.array([-3,4])
lengthV1 = np.sqrt(np.dot(v1,v1))
lengthV2 = np.sqrt(np.dot(v2,v2))
ang = np.rad2deg(np.arccos( np.dot(v1,v2) / (lengthV1 * lengthV2)))
print('Angle between Vectors - %s' %ang)

Angle between Vectors - 90.0


# Inner & outer products

In [39]:
# v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.inner(v1,v2)
print("\n Inner Product ==> \n", np.inner(v1,v2))
print("\n Outer Product ==> \n", np.outer(v1,v2))


 Inner Product ==> 
 32

 Outer Product ==> 
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


# vector cross product

In [38]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
print("\nVector Cross Product ==> \n", np.cross(v1,v2))


Vector Cross Product ==> 
 [-3  6 -3]
