# MATRIX CREATION 

In [2]:
import numpy as np

In [2]:
# Create a 4x4 matrix
A = np.array([[1,2,3,4] , [5,6,7,8] , [10 , 11 , 12 ,13] , [14,15,16,17]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [4]:
# Datatype of Matrix
A.dtype

dtype('int32')

In [5]:
B = np.array([[1.5,2.07,3,4] , [5,6,7,8] , [10 , 11 , 12 ,13] , [14,15,16,17]])
B

array([[ 1.5 ,  2.07,  3.  ,  4.  ],
       [ 5.  ,  6.  ,  7.  ,  8.  ],
       [10.  , 11.  , 12.  , 13.  ],
       [14.  , 15.  , 16.  , 17.  ]])

In [6]:
# Datatype of Matrix
B.dtype

dtype('float64')

In [7]:
# Shape of Matrix
A.shape

(4, 4)

In [8]:
# Generate a 4x4 zero matrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#Shape of Matrix
z1 = np.zeros((4,4))
z1.shape

(4, 4)

In [12]:
# Generate a 5x5 matrix filled with ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Return 10x10 matrix of random integer numbers between 0 to 500
np.random.randint(0,500, (10,10))

array([[358, 349, 299,  96, 240, 384, 317, 428, 193, 313],
       [342, 172, 184, 280,  24, 481, 448, 231, 296, 491],
       [154, 346,  42,  29,  74, 407, 104,  27,   2, 353],
       [319, 368, 179, 241, 358, 357, 130, 314,  66, 414],
       [208, 483, 180, 394,  98, 436,  10,  50, 340,   7],
       [ 79,  59, 160, 307,  92, 132, 429, 274, 349, 264],
       [102, 497, 263, 398, 314, 338,  93, 306,  86, 350],
       [ 13, 312, 377, 471,  71, 134, 109, 116, 115, 266],
       [199, 288, 362, 298, 298, 187,  81, 248, 278, 498],
       [468, 117, 375, 215, 130, 311,  92, 335, 172, 212]])

In [14]:
mat1 = np.random.randint(0,1000,100).reshape(10,10)
mat1

array([[799, 883,  15, 276, 809, 837,  79,  39, 177, 149],
       [894, 320, 270, 334, 847, 876, 916, 593, 702, 580],
       [979, 329, 616, 471, 390,   0, 822, 616, 124, 121],
       [704, 787, 702, 133, 717, 470, 602, 215, 201, 736],
       [380, 723, 196, 280, 177, 926,  74, 346, 427, 849],
       [396, 436, 324, 774, 468, 916, 691, 920, 467, 989],
       [415, 708, 400, 956, 484, 104, 854, 116, 465, 640],
       [955,  21, 562, 165, 230, 912, 477, 733, 199,  58],
       [512, 916, 883, 868, 419, 680, 734, 312, 703, 588],
       [123, 922, 844, 939, 658, 190, 364,   0, 534, 863]])

In [15]:
mat1[0,0]

799

In [16]:
mat1[mat1 > 500]

array([799, 883, 809, 837, 894, 847, 876, 916, 593, 702, 580, 979, 616,
       822, 616, 704, 787, 702, 717, 602, 736, 723, 926, 849, 774, 916,
       691, 920, 989, 708, 956, 854, 640, 955, 562, 912, 733, 512, 916,
       883, 868, 680, 734, 703, 588, 922, 844, 939, 658, 534, 863])

In [17]:
# Identity Matrix
i=np.eye(9)
i

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [22]:
#diagonal matrix
D = np.diag([1,2,3,4,5,6,7,8])
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [23]:
# Traingular Matrices (lower & Upper triangular matrix) :
M = np.random.randn(5,5)     #from normaldistbn
U = np.triu(M)
L = np.tril(M)
print("  matrix - \n" , M)
print("\n")
print("lower triangular matrix - \n" , L)
print("\n")
print("Upper triangular matrix - \n" , U)

  matrix - 
 [[-0.44002652  0.47712791 -0.23018672  0.26280053  0.34681991]
 [ 1.0535635  -0.33049952  0.16633696  0.78887004 -1.29692695]
 [-0.1610638   0.04972183  0.32530996 -1.3920912   1.4784657 ]
 [-1.64025696 -0.34258556 -0.56482867 -1.13112098  0.74217124]
 [ 0.12823593 -0.88775741 -0.04397114  0.58603071  1.55273516]]


lower triangular matrix - 
 [[-0.44002652  0.          0.          0.          0.        ]
 [ 1.0535635  -0.33049952  0.          0.          0.        ]
 [-0.1610638   0.04972183  0.32530996  0.          0.        ]
 [-1.64025696 -0.34258556 -0.56482867 -1.13112098  0.        ]
 [ 0.12823593 -0.88775741 -0.04397114  0.58603071  1.55273516]]


Upper triangular matrix - 
 [[-0.44002652  0.47712791 -0.23018672  0.26280053  0.34681991]
 [ 0.         -0.33049952  0.16633696  0.78887004 -1.29692695]
 [ 0.          0.          0.32530996 -1.3920912   1.4784657 ]
 [ 0.          0.          0.         -1.13112098  0.74217124]
 [ 0.          0.          0.          0.  

In [24]:
# Generate a 5X5 matrix with a given fill value of 8
np.full((5,5) , 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [25]:
# Generate 5X5 matrix of Random float numbers between 10 to 20
np.random.uniform(10,20, size=(5,5))

array([[10.33072194, 19.32720602, 17.34041677, 10.6955983 , 12.00788761],
       [10.51470161, 15.04447902, 14.10489905, 19.19289154, 11.89433734],
       [10.4915881 , 15.96502494, 17.50348779, 14.22593559, 19.32946255],
       [18.86611093, 10.76026529, 11.08031857, 18.46537892, 16.4068248 ],
       [10.69475641, 10.65669537, 13.24556071, 16.92000396, 12.6936003 ]])

In [26]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [3]:
# Collapse Matrix into one dimension array
print(A.flatten())
print(A.ravel())

[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17]
[ 1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17]


# Reading elements of a Matrix

In [4]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [10]:
# Fetch first row of matrix
A[0,:]

array([1, 2, 3, 4])

In [11]:
# Fetch first column of matrix
A[:,0]

array([ 1,  5, 10, 14])

In [12]:
# Fetch first element of the matrix
A[0,0]

1

In [13]:
A[1:3 , 1:3]

array([[ 6,  7],
       [11, 12]])

# Reverse Rows / Columns of a Matrix

In [14]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
# Reverse rows
arr[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [16]:
# Reverse colunms
arr[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

# SWAP Rows & Columns

In [5]:
m1 = np.arange(0,16).reshape(4,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
# SWAP rows 0 & 1
m1[[0,1]] = m1[[1,0]]
m1

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
# SWAP rows 2 & 3
m1[[3,2]] = m1[[2,3]]
m1

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [6]:
# Swap columns 2 & 3
m1[:,[2, 3]] = m1[:,[3, 2]]
m1

array([[ 0,  1,  3,  2],
       [ 4,  5,  7,  6],
       [ 8,  9, 11, 10],
       [12, 13, 15, 14]])

# Concatenate Matrices

In [7]:
A = np.array([[1,2] , [3,4] ,[5,6]])
B = np.array([[1,1] , [1,1]])
C = np.concatenate((A,B))
C

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [1, 1]])

# Matrix Addition

In [8]:
#********************************************************#
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M) ==> \n", M)
print("\n Second Matrix (N) ==> \n", N)
C = M+N
print("\n Matrix Addition (M+N) ==> \n", C)
# OR
C = np.add(M,N,dtype = np.float64)
print("\n Matrix Addition using np.add ==> \n", C)



 First Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Addition (M+N) ==> 
 [[ 2  3  4]
 [ 6 -1  8]
 [10 11  3]]

 Matrix Addition using np.add ==> 
 [[ 2.  3.  4.]
 [ 6. -1.  8.]
 [10. 11.  3.]]


# Matrix subtraction

In [9]:
#********************************************************#
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M) ==> \n", M)
print("\n Second Matrix (N) ==> \n", N)
C = M-N
print("\n Matrix Subtraction (M-N) ==> \n", C)
# OR
C = np.subtract(M,N,dtype = np.float64)
print("\n Matrix Subtraction using np.subtract ==> \n", C)



 First Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Subtraction (M-N) ==> 
 [[ 0  1  2]
 [ 2 -5  4]
 [ 4  5 -3]]

 Matrix Subtraction using np.subtract ==> 
 [[ 0.  1.  2.]
 [ 2. -5.  4.]
 [ 4.  5. -3.]]


# Matrices Scalar Multiplication

In [10]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
C = 10
print("\n Matrix (M) ==> \n", M)
print("\nMatrices Scalar Multiplication ==> \n", C*M)
# OR
print("\nMatrices Scalar Multiplication ==> \n", np.multiply(C,M))


 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Matrices Scalar Multiplication ==> 
 [[ 10  20  30]
 [ 40 -30  60]
 [ 70  80   0]]

Matrices Scalar Multiplication ==> 
 [[ 10  20  30]
 [ 40 -30  60]
 [ 70  80   0]]


# Transpose of a matrix

In [11]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M) ==> \n", M)
print("\nTranspose of M ==> \n", np.transpose(M))
# OR
print("\nTranspose of M ==> \n", M.T)


 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Transpose of M ==> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]

Transpose of M ==> 
 [[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


# Determinant of a matrix

In [12]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M) ==> \n", M)
print("\nDeterminant of M ==> ", np.linalg.det(M))


 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Determinant of M ==>  195.0


# Rank of a matrix

In [13]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M) ==> \n", M)
print("\nRank of M ==> ", np.linalg.matrix_rank(M))


 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Rank of M ==>  3


# Trace of matrix

In [14]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M) ==> \n", M)
print("\nTrace of M ==> ", np.trace(M))


 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Trace of M ==>  -2


# Inverse of matrix A

In [15]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M) ==> \n", M)
print("\nInverse of M ==> \n", np.linalg.inv(M))


 Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Inverse of M ==> 
 [[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


# Matrix Multiplication (pointwise multiplication)

In [16]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M) ==> \n", M)
print("\n Second Matrix (N) ==> \n", N)
print("\n Point-Wise Multiplication of M & N ==> \n", M*N)
# OR
print("\n Point-Wise Multiplication of M & N ==> \n", np.multiply(M,N))


 First Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Point-Wise Multiplication of M & N ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]

 Point-Wise Multiplication of M & N ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


# Matrix dot product

In [17]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M) ==> \n", M)
print("\n Second Matrix (N) ==> \n", N)
print("\n Matrix Dot Product ==> \n", M@N)
# OR
print("\n Matrix Dot Product using np.matmul ==> \n", np.matmul(M,N))
# OR
print("\n Matrix Dot Product using np.dot ==> \n", np.dot(M,N))


 First Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Dot Product ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]

 Matrix Dot Product using np.matmul ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]

 Matrix Dot Product using np.dot ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]


# Matrix Division

In [18]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M) ==> \n", M)
print("\n Second Matrix (N) ==> \n", N)
print("\n Matrix Division (M/N) ==> \n", M/N)
# OR
print("\n Matrix Division (M/N) ==> \n", np.divide(M,N))


 First Matrix (M) ==> 
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Division (M/N) ==> 
 [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]

 Matrix Division (M/N) ==> 
 [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]


# Sum of all elements in a matrix

In [19]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n Matrix (N) ==> \n", N)
print ("Sum of all elements in a Matrix ==>")
print (np.sum(N))


 Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Sum of all elements in a Matrix ==>
18


# Column-Wise Addition

In [21]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n Matrix (N) ==> \n", N)
print ("Column-Wise summation ==> ")
print (np.sum(N,axis=0))


 Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Column-Wise summation ==> 
[6 6 6]


# Row-Wise Addition

In [22]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n Matrix (N) ==> \n", N)
print ("Row-Wise summation ==>")
print (np.sum(N,axis=1))


 Matrix (N) ==> 
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Row-Wise summation ==>
[3 6 9]


# Kronecker Product of matrices

In [23]:
M1 = np.array([[1,2,3] , [4,5,6]])
M1

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
M2 = np.array([[10,10,10],[10,10,10]])
M2

array([[10, 10, 10],
       [10, 10, 10]])

In [25]:
np.kron(M1,M2)

array([[10, 10, 10, 20, 20, 20, 30, 30, 30],
       [10, 10, 10, 20, 20, 20, 30, 30, 30],
       [40, 40, 40, 50, 50, 50, 60, 60, 60],
       [40, 40, 40, 50, 50, 50, 60, 60, 60]])

# Matrix Powers

In [26]:
M1 = np.array([[1,2],[4,5]])
M1

array([[1, 2],
       [4, 5]])

In [27]:
#Matrix to the power 3
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [28]:
#Matrix to the power 3
np.linalg.matrix_power(M1,3)

array([[ 57,  78],
       [156, 213]])

# Tensor

In [3]:
# Create Tensor
T1 = np.array([
 [[1,2,3], [4,5,6], [7,8,9]],
 [[10,20,30], [40,50,60], [70,80,90]],
 [[100,200,300], [400,500,600], [700,800,900]],
 ])
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [4]:
T2 = np.array([
 [[0,0,0] , [0,0,0] , [0,0,0]],
 [[1,1,1] , [1,1,1] , [1,1,1]],
 [[2,2,2] , [2,2,2] , [2,2,2]]

])
T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

# Tensor Addition

In [5]:
A = T1+T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [6]:
np.add(T1,T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

# Tensor Subtraction

In [7]:
S = T1-T2
S

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [8]:
np.subtract(T1,T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

# Tensor Element-Wise Product

In [9]:
P = T1*T2
P

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [11]:
np.multiply(T1,T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

# Tensor Element-Wise Division

In [13]:
D = T1/T2
D

C:\Users\Admin\AppData\Local\Temp\ipykernel_10184\2993674564.py:1: RuntimeWarning: divide by zero encountered in true_divide
  D = T1/T2


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [15]:
np.divide(T1,T2)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10184\2692294074.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(T1,T2)


array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

# Tensor Dot Product

In [16]:
np.tensordot(T1,T2)

array([[  63,   63,   63],
       [ 630,  630,  630],
       [6300, 6300, 6300]])

# Solving Equations
𝐴𝑋 = 𝐵


In [17]:
A = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
B = np.random.random((3,1))
B

array([[0.65033776],
       [0.79341157],
       [0.78857106]])

In [19]:
# Ist Method
X = np.dot(np.linalg.inv(A) , B)
X

array([[ 6.66146835e+14],
       [-1.33229367e+15],
       [ 6.66146835e+14]])

In [20]:
# 2nd Method
X = np.matmul(np.linalg.inv(A) , B)
X

array([[ 6.66146835e+14],
       [-1.33229367e+15],
       [ 6.66146835e+14]])

In [21]:
# 3rd Method
X = np.linalg.inv(A)@B
X

array([[ 6.66146835e+14],
       [-1.33229367e+15],
       [ 6.66146835e+14]])

In [22]:
# 4th Method
X = np.linalg.solve(A,B)
X

array([[ 6.66146835e+14],
       [-1.33229367e+15],
       [ 6.66146835e+14]])